drivers_2025 = [
    {"name": "Max Verstappen", "shortcode": "VER"},
    {"name": "Liam Lawson", "shortcode": "LAW"},
    {"name": "Lewis Hamilton", "shortcode": "HAM"},
    {"name": "George Russell", "shortcode": "RUS"},
    {"name": "Charles Leclerc", "shortcode": "LEC"},
    {"name": "Andrea Kimi Antonelli", "shortcode": "ANT"},
    {"name": "Lando Norris", "shortcode": "NOR"},
    {"name": "Oscar Piastri", "shortcode": "PIA"},
    {"name": "Fernando Alonso", "shortcode": "ALO"},
    {"name": "Lance Stroll", "shortcode": "STR"},
    {"name": "Esteban Ocon", "shortcode": "OCO"},
    {"name": "Jack Doohan", "shortcode": "DOO"},
    {"name": "Pierre Gasly", "shortcode": "GAS"},
    {"name": "Yuki Tsunoda", "shortcode": "TSU"},
    {"name": "Isack Hadjar", "shortcode": "HAD"},
    {"name": "Alexander Albon", "shortcode": "ALB"},
    {"name": "Carlos Sainz", "shortcode": "SAI"},
    {"name": "Nico Hülkenberg", "shortcode": "HUL"},
    {"name": "Gabriel Bortoleto", "shortcode": "BOR"},
    {"name": "Franco Colapinto", "shortcode": "COL"},
]
