races_2025 = [
    {"full_name": "Australian Grand Prix", "short_name": "Australia"},
    {"full_name": "Saudi Arabian Grand Prix", "short_name": "Saudi Arabia"},
    {"full_name": "Chinese Grand Prix", "short_name": "China"},
    {"full_name": "Japanese Grand Prix", "short_name": "Japan"},
    {"full_name": "Bahrain Grand Prix", "short_name": "Bahrain"},
    {"full_name": "Miami Grand Prix", "short_name": "Miami"},
    {"full_name": "Emilia Romagna Grand Prix", "short_name": "Emilia Romagna"},
    {"full_name": "Monaco Grand Prix", "short_name": "Monaco"},
    {"full_name": "Canadian Grand Prix", "short_name": "Canada"},
    {"full_name": "Spanish Grand Prix", "short_name": "Spain"},
    {"full_name": "Austrian Grand Prix", "short_name": "Austria"},
    {"full_name": "British Grand Prix", "short_name": "Great Britain"},
    {"full_name": "Hungarian Grand Prix", "short_name": "Hungary"},
    {"full_name": "Belgian Grand Prix", "short_name": "Belgium"},
    {"full_name": "Dutch Grand Prix", "short_name": "Netherlands"},
    {"full_name": "Italian Grand Prix", "short_name": "Italy"},
    {"full_name": "Azerbaijan Grand Prix", "short_name": "Azerbaijan"},
    {"full_name": "Singapore Grand Prix", "short_name": "Singapore"},
    {"full_name": "United States Grand Prix", "short_name": "United States"},
    {"full_name": "Mexican Grand Prix", "short_name": "Mexico"},
    {"full_name": "Brazilian Grand Prix", "short_name": "Brazil"},
    {"full_name": "Las Vegas Grand Prix", "short_name": "Las Vegas"},
    {"full_name": "Qatar Grand Prix", "short_name": "Qatar"},
    {"full_name": "Abu Dhabi Grand Prix", "short_name": "Abu Dhabi"},
]